# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jmfermun/development/repositories/mastering_embedded_linux_programming/yocto/poky/meta \
  /home/jmfermun/development/repositories/mastering_embedded_linux_programming/yocto/poky/meta-poky \
  /home/jmfermun/development/repositories/mastering_embedded_linux_programming/yocto/poky/meta-yocto-bsp \
  /home/jmfermun/development/repositories/mastering_embedded_linux_programming/yocto/meta-nova \
  "
