DISTRO_NAME = "Mackerel (Mackerel Embedded Linux Distro)"
DISTRO_VERSION = "0.1"

# DISTRO_FEATURES: Add software support for these features.
# DISTRO_EXTRA_RDEPENDS: Add these packages to all images.
# DISTRO_EXTRA_RRECOMMENDS: Add these packages if they exist.
# TCLIBC: Select this version of the C standard library.
